services:
  app:
    image: airlab-project:latest
    container_name: airlab-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://116.110.153.73:8080/airlabsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Strong@Password123!
