version: "3.8"

services:
  app:
    build: .
    container_name: airlab-app
    restart: always

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d5nikj6mcj7s73cmuke0-a.singapore-postgres.render.com:5432/my_spring_db_kzpc?sslmode=require
      SPRING_DATASOURCE_USERNAME: my_spring_db_kzpc_user
      SPRING_DATASOURCE_PASSWORD: Fwt5R1ELLvDIw7UJVqiet7bRNHAIXPys

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      API_KEY_AIRLABS: 30902306-ac71-41b0-a03d-475d5f1df007

networks:
    default:
        driver: bridge