name: CI - Build and Push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build jar
        run: mvn clean package -DskipTests

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build & Push image (latest + commit SHA)
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE=${{ secrets.DOCKER_USERNAME }}/airlab

          docker build -t $IMAGE:latest -t $IMAGE:$TAG .

          docker push $IMAGE:latest
          docker push $IMAGE:$TAG


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.EC2_IP }}
  #         username: ubuntu
  #         key: ${{ secrets.EC2_KEY }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/airlab:latest
  #           docker stop airlab || true
  #           docker rm airlab || true
  #           docker run -d -p 80:8080 \
  #             -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
  #             -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
  #             -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
  #             -e AIRLABS_KEY=${{ secrets.AIRLABS_KEY }} \
  #             --name airlab ${{ secrets.DOCKER_USERNAME }}/airlab:latest
